### ISSUE TITLE
Issue while installing non root apk

### ISSUE THREAD

**Issue by Freakishink292** [Pinball3D/Rabbit-R1#2]
While installing the APK through adb, this happens:
`Performing Streamed Install
adb: failed to install Rabbit R1.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1814426092.tmp/base.apk (at Binary XML file line #0): Requires newer sdk version #32 (current version is #30)]`

**Comment by Fast0n** [comment]
You must use a device with Android 12 or higher.

**Comment by Freakishink292** [comment]
Oh, I didn't know that. I was using Android 11. I don't have any Android 12-14 devices, so I'm going to have to close this as unplanned.
